### ISSUE TITLE
Palette specification

### ISSUE THREAD

**Issue by mbutler808** [kingaa/ouch#4]
Looks great Aaron! Thank you very much for your work. I think to make the palette customizable, though I think you need to put a conditional on this 
https://github.com/kingaa/ouch/blob/3dec2ce1fcbaaa430f7543d66301dc40dd3af51a/R/plot.R#L54

```
 if (is.null(palette)) palette <- rainbow(length(levs))
```

Otherwise users will have to write a function to customize that takes as an argument the length of levels. I guess I was thinking that users could just specify a vector of colors. Something along the lines of c("reg1"="red", "reg2"="blue", "reg2="black")

**Comment by kingaa** [comment]
But by default, `palette=rainbow`.  See https://github.com/kingaa/ouch/blob/3dec2ce1fcbaaa430f7543d66301dc40dd3af51a/R/plot.R#L150

**Comment by mbutler808** [comment]
Yes, I saw that. Sorry. I guess we want default palette = NULL, and if (is.null(palette)) palette=rainbow( length(levs))  ?

**Comment by mbutler808** [comment]
Or is 
```
if (palette==rainbow) palette <- rainbow(length(levs))
```
a valid check?  Otherwise use the vector specified ?

**Comment by mbutler808** [comment]
So I tried changing the default palette = rainbow in an tree plot, and it had no effect. I thought that rainbow(length(levs)) would return a vector of hex color codes, so I tried writing a dummy function 'mypal' that would return the same type of object:
```
col2hex <- function(cc) {rgb(col2rgb(cc)[1], col2rgb(cc)[2], col2rgb(cc)[3], maxColorValue=255)}

mypal <- function(x){return(c(col2hex("black"), col2hex("blue"), col2hex("purple")))}

data(bimac)
tree <- with(bimac,ouchtree(node,ancestor,time/max(time),species))

plot(tree,regimes=bimac["OU.LP"], palette=mypal)   # no effect
plot(tree,regimes=bimac["OU.LP"], palette= c("black", "blue", "purple"))   # no effect
```
I don't understand why specifying palette does nothing. It is a parameter to the plot function. Is it masked some how?

**Comment by kingaa** [comment]
Are you running the [*plotting* branch](https://github.com/kingaa/ouch/tree/plotting)?  It works for me.  Will merge the *plotting* branch in when we are finished with it.

**Comment by kingaa** [comment]
I've merged these changes to the master branch.  Please have a look.

**Comment by mbutler808** [comment]
Thank you! It does work. Sorry for the delay.  
Had figured out how to install from branch yesterday, lol. But I didnʻt have time to reply. It works but itʻs kind of awkward:
```
plot(tree, regimes=bimac["OU.LP"], palette=function(x)return(c("blue", "turquoise", "pink")))
```
Was the simplest implementation I could find. How about if we could also supply a vector? in tree.plot.internal:
```
  ifelse (class(palette)=="function", palette(length(levs)), palette) 
```
Then a vector could be supplied.

**Comment by kingaa** [comment]
Will do.
