### ISSUE TITLE
Long labels

### ISSUE THREAD

**Issue by mbutler808** [kingaa/ouch#5]
Hi Aaron, 
This was actually the issue that really got me to hack the code. Real data exploration often involves long labels and if it is cut off, it can be a big problem to check if your regimes are correctly specified. This canʻt be fixed by making the text smaller sometimes because the region is set as a hard limit based on the node times   
```
  rx <- range(x@times,na.rm=T)
  rxd <- 0.1*diff(rx)
```
In the phylogeny weʻre working on now, there are a lot of unnamed species (and long names). Sometimes we have to paste the names and sites together. We can write short codes, of course, for the species but the human brain can only process so much and with 250 taxa its really a problem. 

https://github.com/kingaa/ouch/blob/3dec2ce1fcbaaa430f7543d66301dc40dd3af51a/R/plot.R#L79

My suggestion is to use the strwidth function to automatically size the plot region for the labels. This requires a cex= argument as cex is then passed to both the plot() and the text() functions. The other annoyance is that the x-axis labels then extends across the names too. I couldnʻt figure out how to limit that. 

```
                xlim=rx+c(-rxd,rxd+max(strwidth(labels, units="figure", cex=cex))),
```

I generated these plots with the edits suggested and arguments 
```
par(mar=c(2,0,0,0))
tree.plot.internal(ox, labels=labels, regimes=oreos, frame.plot=F, ladderize=F, legend=T, palette=c("black", "red", "pink", "green"), text_opts=list(pos=4, cex=.2), legend_opts=list(lwd=3, bty="n"), cex=.2)
```
[namescut.pdf](https://github.com/kingaa/ouch/files/6178467/namescut.pdf)
[namesok.pdf](https://github.com/kingaa/ouch/files/6178469/namesok.pdf)

**Comment by kingaa** [comment]
Getting the width of strings right is complicated: it depends on the font, the specific letters, etc.  I looked into it awhile back and came away shaking my head.  How about just giving the user an option (say, `labelwidth`, default = 0.1) which specifies the width of the label panels.  A bit of trial-and-error will then get it right.

**Comment by mbutler808** [comment]
Sure, that would work too!   
I would like to update the help pages to provide more examples and explanation. Would you be OK with that? I saw that it is now autogenerated from Roxygen, so I will have to study that first. M

**Comment by kingaa** [comment]
Happy to consider pull requests with documentation changes, as well as additional plotting options.  It might also be good to add additional data sets.  The primates data you sent earlier is sitting on the repo now, but not included in the package.  Not sure if it is a good one.

**Comment by kingaa** [comment]
One thing to keep in mind in this is that **ouch** is deficient in unit tests.  With each proposed change, it would be good to include tests (in the `tests` directory) that test the new functionality.

**Comment by kingaa** [comment]
Using the [*plotting* branch](https://github.com/kingaa/ouch/tree/plotting), I can do the following.  Is this an improvement?  I'm not sure: seems a lot of clunkiness just to adjust label widths.

```
with(bimac,ouchtree(node,ancestor,time,species)) -> tr
plot(tr)
plot(tr,text_opts=list(cex=1,pos=4))
plot(tr,text_opts=list(cex=0.5,pos=4))

bimac$silly <- ifelse(
  is.na(bimac$species),
  NA_character_,
  "anamagrophilexitudinousityarpificationesqueness"
)

with(bimac,ouchtree(node,ancestor,time,silly)) -> tr
plot(tr,text_opts=list(pos=4))
plot(tr,text_opts=list(cex=0.5,pos=4))

with(bimac,ouchtree(node,ancestor,time/max(time),silly)) -> tr
plot(tr,text_opts=list(pos=4))
plot(tr,text_opts=list(cex=0.5,pos=4))
```
